"""add category to books

Revision ID: 25f34793619f
Revises: 244f00c88556
Create Date: 2024-02-22 01:33:54.010137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f34793619f'
down_revision = '244f00c88556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'category', ['Category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Category_id')

    # ### end Alembic commands ###
